[project]
name = "study"
version = "1.0.0"
description = "study flask"
dependencies = [
	"flask",
	"python-dotenv",
	"email_validator",
	"build",
	"waitress"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"